FROM node:12.6.0-alpine

ARG gitcommithash

RUN apk add --no-cache curl unzip

RUN echo "Based on commit: $gitcommithash"
RUN mkdir -p /opt && cd /opt && \
    curl -ssL -o frontend.zip https://github.com/repronim/reproschema-ui/archive/${gitcommithash}.zip && \
    unzip frontend.zip && rm frontend.zip && \
    mv reproschema-ui* frontend && cd frontend && \
    npm install && npm run build && \
    grep -rl "/static" dist/ | xargs sed -i 's#/static#/voice-up/static#g'

WORKDIR /opt/frontend
ENTRYPOINT ["node", "server.js"]
